milvus_host: "localhost"
milvus_port: "19530"
milvus_collection_name: "copyright_embeddings"

metadata_id_field: "metadata_id"
embedding_version_field: "embedding_version"
clip_vector_field: "clip_embedding"
cnn_vector_field: "cnn_embedding"

clip_weight: 0.4
cnn_weight: 0.6

top_k_internal: 3
top_k_external: 3

milvus_search_metric: "COSINE"

feature_service_url: "http://localhost:8002/extract"
internal_images_dir: "../database/internal_images"
metadata_service_url: "http://localhost:8006/metadata"
