feature_service_url: "http://localhost:8002/extract"
web_search_service_url: "http://localhost:8001/search"
similarity_service_url: "http://localhost:8003/similarity"
decision_service_url: "http://localhost:8005/decision"
metadata_service_url: "http://localhost:8006/metadata"
embedding_service_url: "http://localhost:8003/embeddings"

max_file_size: 10485760   # 10MB

request_timeout: 20

cloudinary:
  folder: "copyright-registrations"
