feature_service_url: "http://localhost:8002/extract"
web_search_service_url: "http://localhost:8001/search"
similarity_service_url: "http://localhost:8003/similarity"
decision_service_url: "http://localhost:8005/decision"
metadata_service_url: "http://localhost:8006/metadata"
embedding_service_url: "http://localhost:8003/embeddings"

max_file_size: 5242880   # 5MB

request_timeout: 20

cloudinary:
  cloud_name: "daz3btopf"
  api_key: "696374738892441"
  api_secret: "B8JtgyGy_Rk1pJ1b_6P4TgGvFG8"
  folder: "copyright-registrations"
